logging:
  level:
    root: warn

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - dev-a
    - dev-b
    - dev-c
    - d
  description: |-
    line 1 hello world
    line 2 xxx
    line 3 separate dev

